### ISSUE TITLE
Nested objects/arrays

### ISSUE THREAD

**Issue by lukeschafer** [amogram/NMockaroo#5]
I can't figure out how to get nmockaroo to not explode when dealing with nested objects/arrays. At the very least I would expect them to be ignored. I can't find any attributes for dealing with it and the tests are unhelpful

```
public class Job
{
    [MockarooInfo(Type = DataTypes.Guid)]
    public string Id { get; set; }

    public DeliveryDetails DeliveryDetails { get; set; }
}

public class DeliveryDetails
{
        ... etc ...
}
```

**Comment by amogram** [comment]
@lukeschafer - thanks for raising this issue.

I've taken a look and indeed this is a bug.  Properties that are not decorated with Mockaroo attributes should be ignored. 

I'll pop in a fix later and publish a new nuget package.

**Comment by lukeschafer** [comment]
Hey, cool thanks :)

**Comment by amogram** [comment]
The bug has been fixed and a new package is on nuget. 

Thanks again for reporting this issue.

**Comment by lukeschafer** [comment]
Awesome thanks!
