### ISSUE TITLE
Using NMockaroo without attributes

### ISSUE THREAD

**Issue by webJose** [amogram/NMockaroo#6]
Your library is promising, but I would not want to include mock-related code to the project.  Your library, as I understood it, requires that I decorate the properties in order to specify the mockaroo data type.  This is something I would be unwilling to do because it would require mock code inclusion in the domain classes.

Ideally there should be an alternate method to specify the data type for each property without decorating the properties.

Anyway, that would be it.  Let me know your thoughts.  Thank you very much.

**Comment by amogram** [comment]
Hi! Thanks for taking the time to leave feedback about NMockaroo. This project has not been at the forefront of my mind lately.  Sorry for taking so long to replying to you.

I completely agree with your analysis. I wouldn't like to add attributes to my domain model in my current projects either.  The idea of adding such a dependency to my core domain classes fill me with dread.

This little project satisfied a need I had a couple of years ago.  If I was to do it again, I'd do something like defining a type of `Schema<T>` thereby allowing the core domain objects to be the dependency, not the other way around.  Take a look my `dev` branch to see some ideas I've been playing around with.  If I get some inspiration some evening, I'll try and take it further.

Thanks again!
